package com.assets.dao.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bill_phone
 */
public class TBillPhone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_phone.ID
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   运单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_phone.bill_code
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    private String billCode;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_phone.phone_num
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    private String phoneNum;

    /**
     * Database Column Remarks:
     *   状态(0-待处理)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_phone.status
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bill_phone.create_time
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_phone.ID
     *
     * @return the value of t_bill_phone.ID
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_phone.ID
     *
     * @param id the value for t_bill_phone.ID
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_phone.bill_code
     *
     * @return the value of t_bill_phone.bill_code
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_phone.bill_code
     *
     * @param billCode the value for t_bill_phone.bill_code
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode == null ? null : billCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_phone.phone_num
     *
     * @return the value of t_bill_phone.phone_num
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_phone.phone_num
     *
     * @param phoneNum the value for t_bill_phone.phone_num
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_phone.status
     *
     * @return the value of t_bill_phone.status
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_phone.status
     *
     * @param status the value for t_bill_phone.status
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bill_phone.create_time
     *
     * @return the value of t_bill_phone.create_time
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bill_phone.create_time
     *
     * @param createTime the value for t_bill_phone.create_time
     *
     * @mbg.generated Thu Oct 28 17:12:38 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}